import '@game-portal/shared/themes/casino-a.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from 'next';
import MyApp from '../pages/_app';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  pageProps,
}: Readonly<{
  children: React.ReactNode;
  pageProps: any;
}>) {
  return (
    <html lang="en">
      <body className="dsss">
        <AppRouterCacheProvider>
          <MyApp {...pageProps}>{children}</MyApp>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
