import '@game-portal/shared/themes/casino-b/styles.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from 'next';
import { AppProps } from 'next/app';
import MyApp from '../pages/_app';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  pageProps,
}: Readonly<{
  children: React.ReactNode;
  pageProps: AppProps;
}>) {
  return (
    <html lang="en" data-theme="casino-b">
      <body>
        <AppRouterCacheProvider>
          <MyApp {...pageProps}>{children}</MyApp>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
